// <auto-generated />
using System;
using EFViewAndSPDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFViewAndSPDemo.Migrations
{
    [DbContext(typeof(SPContext))]
    [Migration("20201211105128_AddViewUsers")]
    partial class AddViewUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EFViewAndSPDemo.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 39,
                            FirstName = "Fredrik",
                            LastName = "Johansson"
                        },
                        new
                        {
                            Id = 2,
                            Age = 29,
                            FirstName = "Per",
                            LastName = "Andersson"
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            FirstName = "Anna",
                            LastName = "Hansson"
                        });
                });

            modelBuilder.Entity("EFViewAndSPDemo.User", b =>
                {
                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
